services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
      - ./backend/nginx/conf.d/:/etc/nginx/conf.d/
      - ./backend/certbot/www:/var/www/certbot/
      - ./backend/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    networks:
      - app-network

  backend:
    build:
      dockerfile: dockerfile
      context: .
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env  # Uncomment this if your app needs access to the host filesystem
    networks:
      - app-network
  
  # frontend:
  #   build:
  #     dockerfile: dockerfile
  #     context: ./frontend
  #   container_name: frontend
  #   volumes:
  #       - ./frontend:/var/www/frontend/
  #       - ./.env:/var/www/front/.env
  

networks:
  app-network:
    driver: bridge
