services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    networks:
      - app-network

  app:
    build:
      dockerfile: dockerfile
      context: .
    container_name: app
    restart: always
    env_file:
      - .env  # Uncomment this if your app needs access to the host filesystem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
