# This workflow is triggered when a push event occurs on the 'main' branch.
# It builds and pushes a Docker image to Docker Hub.

name: CD - Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Short SHA
        id: sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: false
          tags: backend-initial:${{ env.short_sha }}

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: false
          tags: frontend-initial:${{ env.short_sha }}

      - name: Install squash
        run: |
          sudo apt install pipx
          pipx install docker-squash

      - name: Squash Image
        run: |
          docker-squash -t alan01777/todo-app-backend:${{ env.short_sha }} backend-initial:${{ env.short_sha }}
          docker-squash -t alan01777/todo-app-frontend:${{ env.short_sha }} frontend-initial:${{ env.short_sha }}


      - name: Tag Latest
        run: |
          docker tag alan01777/todo-app-backend:${{ env.short_sha }} alan01777/todo-app-backend:latest
          docker tag alan01777/todo-app-frontend:${{ env.short_sha }} alan01777/todo-app-frontend:latest

      - name: Push Images
        run: |
          docker push alan01777/todo-app-backend:${{ env.short_sha }}
          docker push alan01777/todo-app-frontend:${{ env.short_sha }}
          docker push alan01777/todo-app-backend:latest
          docker push alan01777/todo-app-frontend:latest

  test-images:
    name: Test Docker pull Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Images
        run: |
          docker pull alan01777/todo-app-frontend:latest
          docker pull alan01777/todo-app-backend:latest

      - name: Create Containers
        run: sudo docker compose up